import express from 'express';
import bookRoutes from './book.routes.js';
import userRoutes from './user.routes.js';
import authenticationRoutes from './authentication.routes.js';
import categoryRoutes from './category.routes.js';
import cartRoutes from './cart.routes.js';
import orderRoutes from './order.routes.js';
const router = express.Router();
router.use('/api', bookRoutes);
router.use('/api', userRoutes);
router.use('/api', authenticationRoutes);
router.use('/api', categoryRoutes);
router.use('/api', cartRoutes);
router.use('/api', orderRoutes);
export default router;
